Sundsvallskommun/pw-parking-permit

- src/main/java/se/sundsvall/parkingpermit/Constants.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/AbstractTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/AddMessageToErrandTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/AutomaticDenialDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/SendDenialDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandPhaseTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyResidentOfMunicipalityTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/DecisionDummyTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/ExecutionDummyTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/followup/FollowUpDummyTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/handling/HandlingDummyTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/InvestigationDummyTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/integration/camunda/CamundaClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/camunda/mapper/CamundaMapper.java
- src/main/java/se/sundsvall/parkingpermit/service/ProcessService.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/AbstractTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/AddMessageToErrandTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/AutomaticDenialDecisionTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/SendDenialDecisionTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandPhaseTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyResidentOfMunicipalityTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/DecisionDummyTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/ExecutionDummyTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/followup/FollowUpDummyTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/handling/HandlingDummyTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/InvestigationDummyTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/camunda/mapper/CamundaMapperTest.java
- src/test/java/se/sundsvall/parkingpermit/service/ProcessServiceTest.java
- Added logic to re use request id from incoming request in the workers
that are executed asynchronously
> Uf 5562 use requestid from incoming request

- src/integration-test/resources/CreateProcess/__files/test001_createProcessForCitizen/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test001_createProcessForCitizen/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test003_createProcessForDecisionNotFinalToFinal/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test003_createProcessForDecisionNotFinalToFinal/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test004_createProcessForCancelInActualization/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test004_createProcessForCancelInActualization/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test005_createProcessForActualizationNotComplete/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test005_createProcessForActualizationNotComplete/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test006_createProcessForSanityChecksFailToPass/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test007_createProcessForPhaseActionNotComplete/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test007_createProcessForPhaseActionNotComplete/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test008_createProcessForCancelInInvestigation/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test008_createProcessForCancelInInvestigation/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test009_createProcessForCardNotExistsToExists/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test009_createProcessForCardNotExistsToExists/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test010_createProcessForCancelnDecision/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test010_createProcessForCancelnDecision/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test011_createProcessValidationErrorInBRToComplete/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test011_createProcessValidationErrorInBRToComplete/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test012_createProcessForDecisionRejected/mappings/1_actualization/07_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test012_createProcessForDecisionRejected/mappings/1_actualization/08_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/integration-test/resources/CreateProcess/__files/test014_createProcessWaitingForStakeholderUpdateInActualization/mappings/1_actualization/09_actualization_update-display-phase-task-worker--api-casedata-patch-errand.json
- src/integration-test/resources/CreateProcess/__files/test014_createProcessWaitingForStakeholderUpdateInActualization/mappings/1_actualization/10_actualization_update-status-task-worker--api-casedata-get-errand.json
- src/main/resources/processmodels/process-parking-permit.bpmn
> UF-10432: Fix typo when setting displayPhase

- src/main/java/se/sundsvall/parkingpermit/Constants.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/AutomaticDenialDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/CheckDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/util/SimplifiedServiceTextProperties.java
- src/main/java/se/sundsvall/parkingpermit/util/TimerUtil.java
- src/main/resources/application.yaml
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/AutomaticDenialDecisionTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/CheckDecisionTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/util/SimplifiedServiceTextPropertiesTest.java
- src/test/java/se/sundsvall/parkingpermit/util/TimerUtilTest.java
> UF-10554: Added processvariable holding time to send control message

- src/integration-test/java/apptest/CreateProcessIT.java
- src/integration-test/java/apptest/ProcessWithDecisionDeviationIT.java
- src/integration-test/java/apptest/ProcessWithInvestigationDeviationIT.java
- src/integration-test/java/apptest/mock/Actualization.java
- src/integration-test/java/apptest/mock/Decision.java
- src/integration-test/java/apptest/mock/Execution.java
- src/integration-test/java/apptest/mock/FollowUp.java
- src/integration-test/java/apptest/mock/Investigation.java
- src/integration-test/java/apptest/mock/api/ApiGateway.java
- src/integration-test/java/apptest/mock/api/BusinessRules.java
- src/integration-test/java/apptest/mock/api/CaseData.java
- src/integration-test/java/apptest/mock/api/Citizen.java
- src/integration-test/java/apptest/mock/api/PartyAssets.java
- src/integration-test/java/apptest/mock/api/Rpa.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/CheckErrandPhaseActionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandPhaseTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyAdministratorStakeholderExistsTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/CheckDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/integration/casedata/mapper/CaseDataMapper.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyAdministratorStakeholderExistsTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/casedata/mapper/CaseDataMapperTest.java
> UF-10811: Changed handling of extraparameters

- src/integration-test/resources/CreateProcess/__files/test002_createProcessForNonCitizen/mappings/send-denial-decision-task-worker---api-messaging-send-web-message.json
- src/main/java/se/sundsvall/parkingpermit/Constants.java
- src/main/java/se/sundsvall/parkingpermit/integration/messaging/mapper/MessagingMapper.java
- src/main/java/se/sundsvall/parkingpermit/service/MessagingService.java
- src/main/resources/integrations/messaging.yaml
- src/test/java/se/sundsvall/parkingpermit/integration/messaging/mapper/MessagingMapperTest.java
- src/test/java/se/sundsvall/parkingpermit/service/MessagingServiceTest.java
> UF-10831: Changed version of Messaging to 5.2

- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/SendSimplifiedServiceTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/integration/messaging/mapper/MessagingMapper.java
- src/main/java/se/sundsvall/parkingpermit/service/MessagingService.java
- src/main/java/se/sundsvall/parkingpermit/util/TextProvider.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/SendSimplifiedServiceTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/messaging/mapper/MessagingMapperTest.java
- src/test/java/se/sundsvall/parkingpermit/service/MessagingServiceTest.java
> UF-10555: Implemented sending message regarding simplified service

- src/integration-test/java/apptest/ProcessWithActualizationDeviationIT.java
- src/integration-test/java/apptest/ProcessWithDecisionDeviationIT.java
- src/integration-test/java/apptest/ProcessWithInvestigationDeviationIT.java
- src/integration-test/java/apptest/mock/Canceled.java
- src/integration-test/java/apptest/verification/ProcessPathway.java
- src/main/java/se/sundsvall/parkingpermit/Constants.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorker.java
- src/main/resources/processmodels/process-parking-permit.bpmn
> UF-11042: Refactored handling when cancel

- src/integration-test/java/apptest/mock/Denial.java
- src/integration-test/java/apptest/mock/Execution.java
- src/integration-test/java/apptest/verification/ProcessPathway.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/SendSimplifiedServiceTaskWorker.java
- src/main/resources/processmodels/process-parking-permit.bpmn
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/SendSimplifiedServiceTaskWorkerTest.java
> UF-11271: Added sending of simplified service in automatic denial

- src/main/java/se/sundsvall/parkingpermit/integration/businessrules/BusinessRulesClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/camunda/CamundaClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/casedata/CaseDataClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/citizen/CitizenClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/messaging/MessagingClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/partyassets/PartyAssetsClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/templating/TemplatingClient.java
> UF-11348: Add Circuitbreakers

- src/integration-test/java/apptest/mock/Denial.java
- src/integration-test/java/apptest/mock/api/CaseData.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/AutomaticDenialDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/CheckAppealTaskWorker.java
- src/main/resources/integrations/case-data.yaml
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/CheckAppealTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyAdministratorStakeholderExistsTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/casedata/mapper/CaseDataMapperTest.java
> UF-10922: Added checks for appeal

- src/integration-test/java/apptest/ProcessWithExecutionDeviationIT.java
- src/integration-test/java/apptest/verification/ProcessPathway.java
- src/main/java/se/sundsvall/parkingpermit/Constants.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/CheckAppealTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/UpdateAssetTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/integration/partyassets/PartyAssetsClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/partyassets/mapper/PartyAssetMapper.java
- src/main/java/se/sundsvall/parkingpermit/service/PartyAssetsService.java
- src/main/resources/processmodels/process-parking-permit.bpmn
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/CheckAppealTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/UpdateAssetTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/partyassets/configuration/mapper/PartyAssetMapperTest.java
- src/test/java/se/sundsvall/parkingpermit/service/PartyAssetsServiceTest.java
> UF-10921: Changed bpmn-model and implemented handling of appeals.

- src/integration-test/java/apptest/ProcessAppealDeviationIT.java
- src/integration-test/java/apptest/ProcessAppealWithoutDeviationIT.java
- src/integration-test/java/apptest/ProcessWithActualizationDeviationIT.java
- src/integration-test/java/apptest/ProcessWithDecisionDeviationIT.java
- src/integration-test/java/apptest/ProcessWithExecutionDeviationIT.java
- src/integration-test/java/apptest/ProcessWithInvestigationDeviationIT.java
- src/integration-test/java/apptest/mock/CheckAppeal.java
- src/integration-test/java/apptest/mock/Execution.java
- src/integration-test/java/apptest/mock/api/PartyAssets.java
- src/integration-test/java/apptest/verification/ProcessPathway.java
- src/integration-test/resources/Wiremock/__files/common/responses/casedata/get-errand.json
- src/integration-test/resources/Wiremock/__files/common/responses/partyassets/get-assets.json
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/UpdateAssetTaskWorker.java
- src/main/resources/processmodels/process-parking-permit.bpmn
> UF-10926: Updated it-tests with appeal cases

- src/integration-test/java/apptest/ProcessErrorHandlingIT.java
> UF-11489: IT-tests for process instance id existVerification.

- src/main/resources/integrations/messaging.yaml
> UF-14635: Update to messaging 6.1

- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorker.java
- src/main/resources/processmodels/process-parking-permit.bpmn
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorkerTest.java
> UF-14333: Refactored UpdateErrandTaskWorker to use status from BPM

- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/SanityCheckTaskWorker.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/SanityCheckTaskWorkerTest.java
> UF-14960: Added dummy worker for supporting older versions of model

- src/integration-test/java/apptest/mock/Actualization.java
- src/integration-test/java/apptest/mock/Canceled.java
- src/integration-test/java/apptest/mock/Decision.java
- src/integration-test/java/apptest/mock/Denial.java
- src/integration-test/java/apptest/mock/Execution.java
- src/integration-test/java/apptest/mock/FollowUp.java
- src/integration-test/java/apptest/mock/Investigation.java
- src/main/java/se/sundsvall/parkingpermit/integration/casedata/mapper/CaseDataMapper.java
- src/main/resources/integrations/case-data.yaml
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/AddMessageToErrandTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/OrderCardTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/casedata/mapper/CaseDataMapperTest.java
> UF-14957: Changed version of CaseData to 11.0

- src/integration-test/java/apptest/mock/Actualization.java
- src/integration-test/java/apptest/mock/Canceled.java
- src/integration-test/java/apptest/mock/Decision.java
- src/integration-test/java/apptest/mock/Denial.java
- src/integration-test/java/apptest/mock/Execution.java
- src/integration-test/java/apptest/mock/FollowUp.java
- src/integration-test/java/apptest/mock/Investigation.java
- src/integration-test/java/apptest/mock/api/CaseData.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/OrderCardTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/integration/casedata/CaseDataClient.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/UpdateErrandStatusTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/OrderCardTaskWorkerTest.java
> Draken-1133: Fix for changed status endpoint

- src/integration-test/java/apptest/ProcessWithExecutionDeviationIT.java
- src/integration-test/java/apptest/mock/Execution.java
- src/integration-test/java/apptest/mock/api/CaseData.java
- src/integration-test/java/apptest/mock/api/PartyAssets.java
- src/integration-test/java/apptest/verification/ProcessPathway.java
- src/integration-test/resources/Wiremock/__files/common/responses/partyassets/get-assets.json
- src/main/java/se/sundsvall/parkingpermit/Constants.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/HandleLostCardTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/integration/casedata/CaseDataClient.java
- src/main/java/se/sundsvall/parkingpermit/integration/casedata/mapper/CaseDataMapper.java
- src/main/java/se/sundsvall/parkingpermit/integration/partyassets/PartyAssetsClient.java
- src/main/java/se/sundsvall/parkingpermit/service/PartyAssetsService.java
- src/main/resources/processmodels/process-parking-permit.bpmn
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyAdministratorStakeholderExistsTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/HandleLostCardTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/casedata/mapper/CaseDataMapperTest.java
- src/test/java/se/sundsvall/parkingpermit/service/PartyAssetsServiceTest.java
> UF-15807: Add handling of lost card

- src/integration-test/java/apptest/mock/Investigation.java
- src/integration-test/java/apptest/mock/api/CaseData.java
- src/integration-test/resources/Wiremock/__files/common/responses/casedata/get-errand.json
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/ConstructDecisionTaskWorker.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/ConstructDecisionTaskWorkerTest.java
> UF-15868: Added validFrom and validTo to decision when automatic

- src/integration-test/java/apptest/mock/Actualization.java
- src/integration-test/java/apptest/mock/api/Citizen.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyResidentOfMunicipalityTaskWorker.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/actualization/VerifyResidentOfMunicipalityTaskWorkerTest.java
> UF-16428: Handle no content from citizen as not citizen of municipality

- src/integration-test/java/apptest/ProcessWithInvestigationDeviationIT.java
- src/integration-test/java/apptest/mock/Investigation.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/ConstructDecisionTaskWorker.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/investigation/ConstructDecisionTaskWorkerTest.java
> UF-16460: Also add status when creating a decision for automatic process

- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/OrderCardTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/integration/rpa/configuration/RpaProperties.java
- src/main/java/se/sundsvall/parkingpermit/service/RpaService.java
- src/main/resources/application-it.yaml
- src/main/resources/application-junit.yaml
- src/main/resources/application.yaml
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/execution/OrderCardTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/rpa/configuration/RpaPropertiesTest.java
- src/test/java/se/sundsvall/parkingpermit/service/RpaServiceTest.java
> UF-16484: Added rpa config that supports folderId per municipality

- src/integration-test/java/apptest/ProcessWithDecisionDeviationIT.java
- src/integration-test/java/apptest/mock/Decision.java
- src/integration-test/java/apptest/mock/DecisionHandlingCase.java
- src/integration-test/java/apptest/mock/DecisionHandlingFollowUp.java
- src/integration-test/java/apptest/mock/api/CaseData.java
- src/integration-test/java/apptest/mock/api/Messaging.java
- src/integration-test/java/apptest/mock/api/PartyAssets.java
- src/integration-test/java/apptest/mock/api/SupportManagement.java
- src/integration-test/java/apptest/mock/api/Templating.java
- src/integration-test/resources/Wiremock/__files/common/responses/messaging/digital-mail.json
- src/main/resources/application-it.yaml
- src/main/resources/application.yaml
- src/main/resources/processmodels/process-parking-permit.bpmn
> UF-16545: Updated flow and added IT-test

- src/integration-test/java/apptest/ProcessWithDecisionDeviationIT.java
- src/integration-test/java/apptest/mock/DecisionHandlingCase.java
- src/integration-test/java/apptest/mock/Denial.java
- src/integration-test/java/apptest/mock/Execution.java
- src/main/java/se/sundsvall/parkingpermit/Constants.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/AddMessageToErrandTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/AutomaticDenialDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/SendDenialDecisionTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/DecisionHandlingTaskWorker.java
- src/main/java/se/sundsvall/parkingpermit/service/MessagingService.java
- src/main/java/se/sundsvall/parkingpermit/util/DenialTextProperties.java
- src/main/resources/application.yaml
- src/main/resources/integrations/messaging.yaml
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/AddMessageToErrandTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/AutomaticDenialDecisionTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/SendDenialDecisionTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/DecisionHandlingTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/service/MessagingServiceTest.java
- src/test/java/se/sundsvall/parkingpermit/util/TextPropertiesTest.java
> UF-16979: Fix for sending decision and changed Messaging version

- src/integration-test/java/apptest/mock/DecisionHandlingCase.java
- src/integration-test/java/apptest/mock/Denial.java
- src/integration-test/java/apptest/mock/Execution.java
- src/main/resources/integrations/messaging.yaml
> UF-17023: Change version of Messaging to 7.3 again

- src/integration-test/java/apptest/ProcessWithDecisionDeviationIT.java
- src/integration-test/resources/Wiremock/__files/common/responses/casedata/get-errand.json
- src/main/resources/integrations/case-data.yaml
- src/main/resources/integrations/support-management.yaml
- src/test/java/se/sundsvall/parkingpermit/businesslogic/worker/decision/DecisionHandlingTaskWorkerTest.java
- src/test/java/se/sundsvall/parkingpermit/integration/supportmanagement/mapper/SupportManagementMapperTest.java
> UF-17393: Change to a fake phone number in test/doc
